CREATE TABLE "annual_p_l_1" (
  "join_key" varchar PRIMARY KEY,
  "Name" varchar,
  "BSE_Code" numeric,
  "NSE_Code" varchar,
  "Industry" varchar,
  "Current_Price" numeric,
  "Sales" numeric,
  "OPM" numeric,
  "Profit_after_tax" numeric,
  "Return_on_capital_employed" numeric,
  "EPS" numeric,
  "Change_in_promoter_holding" numeric,
  "Sales_last_year" numeric,
  "Operating_profit_last_year" numeric,
  "Other_income_last_year" numeric,
  "EBIDT_last_year" numeric,
  "Depreciation_last_year" numeric,
  "EBIT_last_year" numeric,
  "Interest_last_year" numeric,
  "Profit_before_tax_last_year" numeric,
  "Tax_last_year" numeric,
  "Profit_after_tax_last_year" numeric,
  "Extraordinary_items_last_year" numeric,
  "Net_Profit_last_year" numeric,
  "Dividend_last_year" numeric,
  "Material_cost_last_year" numeric,
  "Employee_cost_last_year" numeric,
  "OPM_last_year" numeric,
  "NPM_last_year" numeric,
  "Operating_profit" numeric,
  "Interest" numeric,
  "Depreciation" numeric,
  "EPS_last_year" numeric,
  "EBIT" numeric,
  "Net_profit" numeric,
  "Current_Tax" numeric,
  "Tax" numeric,
  "Other_income" numeric,
  "Last_annual_result_date" varchar,
  "Sales_preceding_year" numeric,
  "Operating_profit_preceding_year" numeric,
  "Other_income_preceding_year" numeric,
  "EBIDT_preceding_year" numeric,
  "Depreciation_preceding_year" numeric,
  "EBIT_preceding_year" numeric,
  "Interest_preceding_year" numeric,
  "Profit_before_tax_preceding_year" numeric,
  "Tax_preceding_year" numeric,
  "Profit_after_tax_preceding_year" numeric,
  "Extraordinary_items_preceding_year" numeric,
  "Net_Profit_preceding_year" numeric,
  "Dividend_preceding_year" numeric,
  "OPM_preceding_year" numeric,
  "NPM_preceding_year" numeric,
  "EPS_preceding_year" numeric,
  "Sales_preceding_12months" numeric,
  "Net_profit_preceding_12months" numeric,
  "Market_Capitalization" numeric
);

CREATE TABLE "annual_p_l_2" (
  "join_key" varchar PRIMARY KEY,
  "Name" varchar,
  "BSE_Code" numeric,
  "NSE_Code" varchar,
  "Industry" varchar,
  "Current_Price" numeric,
  "Sales_growth_3Years" numeric,
  "Sales_growth_5Years" numeric,
  "Profit_growth_3Years" numeric,
  "Profit_growth_5Years" numeric,
  "Sales_growth_10years_median" numeric,
  "Sales_growth_5years_median" numeric,
  "Sales_growth_7Years" numeric,
  "Sales_growth_10Years" numeric,
  "EBIDT_growth_3Years" numeric,
  "EBIDT_growth_5Years" numeric,
  "EBIDT_growth_7Years" numeric,
  "EBIDT_growth_10Years" numeric,
  "EPS_growth_3Years" numeric,
  "EPS_growth_5Years" numeric,
  "EPS_growth_7Years" numeric,
  "EPS_growth_10Years" numeric,
  "Profit_growth_7Years" numeric,
  "Profit_growth_10Years" numeric,
  "Change_in_promoter_holding_3Years" numeric,
  "Average_Earnings_5Year" numeric,
  "Average_Earnings_10Year" numeric,
  "Average_EBIT_5Year" numeric,
  "Average_EBIT_10Year" numeric,
  "Market_Capitalization" numeric
);

ALTER TABLE "annual_p_l_2" ADD FOREIGN KEY ("join_key") REFERENCES "annual_p_l_1" ("join_key");
