CREATE TABLE "annual_p_l_1" (
  "join_key" varchar PRIMARY KEY,
  "Name" varchar,
  "BSE_Code" integer,
  "NSE_Code" varchar,
  "Industry" varchar,
  "Current_Price" integer,
  "Sales" integer,
  "OPM" integer,
  "Profit_after_tax" integer,
  "Return_on_capital_employed" integer,
  "EPS" integer,
  "Change_in_promoter_holding" integer,
  "Sales_last_year" integer,
  "Operating_profit_last_year" integer,
  "Other_income_last_year" integer,
  "EBIDT_last_year" integer,
  "Depreciation_last_year" integer,
  "EBIT_last_year" integer,
  "Interest_last_year" integer,
  "Profit_before_tax_last_year" integer,
  "Tax_last_year" integer,
  "Profit_after_tax_last_year" integer,
  "Extraordinary_items_last_year" integer,
  "Net_Profit_last_year" integer,
  "Dividend_last_year" integer,
  "Material_cost_last_year" integer,
  "Employee_cost_last_year" integer,
  "OPM_last_year" integer,
  "NPM_last_year" integer,
  "Operating_profit" integer,
  "Interest" integer,
  "Depreciation" integer,
  "EPS_last_year" integer,
  "EBIT" integer,
  "Net_profit" integer,
  "Current_Tax" integer,
  "Tax" integer,
  "Other_income" integer,
  "Last_annual_result_date" varchar,
  "Sales_preceding_year" integer,
  "Operating_profit_preceding_year" integer,
  "Other_income_preceding_year" integer,
  "EBIDT_preceding_year" integer,
  "Depreciation_preceding_year" integer,
  "EBIT_preceding_year" integer,
  "Interest_preceding_year" integer,
  "Profit_before_tax_preceding_year" integer,
  "Tax_preceding_year" integer,
  "Profit_after_tax_preceding_year" integer,
  "Extraordinary_items_preceding_year" integer,
  "Net_Profit_preceding_year" integer,
  "Dividend_preceding_year" integer,
  "OPM_preceding_year" integer,
  "NPM_preceding_year" integer,
  "EPS_preceding_year" integer,
  "Sales_preceding_12months" integer,
  "Net_profit_preceding_12months" integer,
  "Market_Capitalization" integer
);

CREATE TABLE "annual_p_l_2" (
  "join_key" varchar PRIMARY KEY,
  "Name" varchar,
  "BSE_Code" integer,
  "NSE_Code" varchar,
  "Industry" varchar,
  "Current_Price" integer,
  "Sales_growth_3Years" integer,
  "Sales_growth_5Years" integer,
  "Profit_growth_3Years" integer,
  "Profit_growth_5Years" integer,
  "Sales_growth_10years_median" integer,
  "Sales_growth_5years_median" integer,
  "Sales_growth_7Years" integer,
  "Sales_growth_10Years" integer,
  "EBIDT_growth_3Years" integer,
  "EBIDT_growth_5Years" integer,
  "EBIDT_growth_7Years" integer,
  "EBIDT_growth_10Years" integer,
  "EPS_growth_3Years" integer,
  "EPS_growth_5Years" integer,
  "EPS_growth_7Years" integer,
  "EPS_growth_10Years" integer,
  "Profit_growth_7Years" integer,
  "Profit_growth_10Years" integer,
  "Change_in_promoter_holding_3Years" integer,
  "Average_Earnings_5Year" integer,
  "Average_Earnings_10Year" integer,
  "Average_EBIT_5Year" integer,
  "Average_EBIT_10Year" integer,
  "Market_Capitalization" integer
);

ALTER TABLE "annual_p_l_2" ADD FOREIGN KEY ("join_key") REFERENCES "annual_p_l_1" ("join_key");
